require: rubocop-rspec

##
## TEMPORARILY disabled 
##


##
## LOCAL PREFERENCES
##
# Allow bigger test cases ('examples')
RSpec/ExampleLength:
  Enabled: true
  Max: 10

Metrics/BlockLength:
  Enabled: false
  Exclude: 
    - spec/**/*

Metrics/AbcSize:
  Enabled: false

# Disable errors due to rspec-specific patterns
RSpec/DescribedClass:
  Enabled: false

##
## DISABLE all layout/whitespace-related errors 
## 

RSpec/FilePath:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/MultilineIfThen:
  Enabled: false

# Style/FileName:
# Enabled: false

# Style/StringLiterals:
# Enabled: false

Style/FormatString:
  Enabled: false

Style/Documentation:
  Enabled: false

